version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.3.0
    container_name: spark-master
    hostname: spark-master
    ports:
      - "17077:7077"
      - "18080:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - HADOOP_CONF_DIR=/etc/hadoop
    volumes:
      - ../hadoop-conf:/etc/hadoop
      - ../workspace:/workspace
      - /etc/hosts:/etc/hosts
