version: '3.8'

services:
  spark-worker:
    image: bitnami/spark:3.3.0
    container_name: spark-worker
    network_mode: host
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://192.168.0.159:17077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - HADOOP_CONF_DIR=/etc/hadoop
    volumes:
      - ../workspace:/workspace
      - ../hadoop-conf:/etc/hadoop
